2.3
SaveliyLipaev/Homework-1-course pull request #1
Opened 2018-10-04 11:38 UTC by SaveliyLipaev

2018-10-04 15:03 UTC, yurii-litvinov requested changes

2018-10-04 15:03 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +				int buffer = mas[j];
Можно const int buffer

2018-10-04 15:03 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +	int *helpMasPos = new int[max + abs(min) + 1]{};
Что-то тут не то. Либо максимум и минимум считаются неправильно для отрицательных чисел, либо тут вполне может оказаться массив с отрицательным размером :)

2018-10-04 15:03 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +			++helpVariable;
Она не столько helpVariable, сколько indexInMainArrayToFill :)

2018-10-04 15:03 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +			mas[helpVariable] = i - abs(min);
И тут, и везде эти abs-ы выглядят очень подозрительно.

2018-10-04 15:03 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +			return 0;
Если функция bool, то она должна возвращать true/false, а не 0/1

2018-10-04 15:22 UTC, SaveliyLipaev commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +	int *helpMasPos = new int[max + abs(min) + 1]{};
Каким образом? у меня max по дефолту нулю равен, там не может быть отрицательного числа, а потом стоит модуль(min), что тоже всегда больше нуля, в итоге если будет массив -6 4 3, то создаться массив из [4+abs(-6)+1]=[11] элементов

2018-10-04 15:36 UTC, SaveliyLipaev commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +			mas[helpVariable] = i - abs(min);
Идея такая: я создаю массив из [max + abs(min) + 1] элементов, если у нас нет отрицательных элементов, то abs(min) вообще никак не будет влиять на программу, но если они есть, то я создаю дополнительные ячейки для них в массиве.
Допустим у нас такой массив : 2 3 -1 5 -2, я создаю массив из [5+2+1]=8 элементов, далее идет такой блок:
for (int i = 0; i < length; ++i)
	{
		++helpMasPos[mas[i] + abs(min)];
	}
На выходе получится что в вспомогательном массиве будут следующие значения:
helpMasPos[0]=1;  то есть одна цифра -2
helpMasPos[1]=1;  то есть одна цифра -1
helpMasPos[2]=0;  то есть ноль цифр 0
helpMasPos[3]=0;  ноль цифр 1
helpMasPos[4]=1;  одна цифра 2
и так далее...
то есть хранит и отрицательные элементы и положительные, а с помощью abs(min) я понимаю какая ячейка за что отвечает
по мне так оптимальный код, даже если мы не будем использовать отрицательные значение, abs(min) будет 0

2018-10-04 17:54 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +	int *helpMasPos = new int[max + abs(min) + 1]{};
А если в массиве только отрицательные числа? Даже так: только очень большие отрицательные числа. Тогда в массиве оказывается куча лишних элементов. Проще было `max - min + 1`, а дальше везде делать `- min` вместо `+ abs(min)`

2018-10-04 18:40 UTC, SaveliyLipaev commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +	int *helpMasPos = new int[max + abs(min) + 1]{};
c abs-ом интуитивно понятнее как по мне
Не знаю видели ли вы это сообщение, еще раз напишу:
Идея такая: я создаю массив из [max + abs(min) + 1] элементов, если у нас нет отрицательных элементов, то abs(min) вообще никак не будет влиять на программу, но если они есть, то я создаю дополнительные ячейки для них в массиве.
Допустим у нас такой массив : 2 3 -1 5 -2, я создаю массив из [5+2+1]=8 элементов, далее идет такой блок:
for (int i = 0; i < length; ++i)
{
++helpMasPos[mas[i] + abs(min)];
}
На выходе получится что в вспомогательном массиве будут следующие значения:
helpMasPos[0]=1; то есть одна цифра -2
helpMasPos[1]=1; то есть одна цифра -1
helpMasPos[2]=0; то есть ноль цифр 0
helpMasPos[3]=0; ноль цифр 1
helpMasPos[4]=1; одна цифра 2
и так далее...
то есть хранит и отрицательные элементы и положительные, а с помощью abs(min) я понимаю какая ячейка за что отвечает
по мне так оптимальный код, даже если мы не будем использовать отрицательные значение, abs(min) будет 0

2018-10-07 19:45 UTC, yurii-litvinov approved these changes
Да, теперь всё хорошо, зачтена

2018-10-07 19:45 UTC, yurii-litvinov commented on Semestr_1/HomeWork_2/Number_3/Number_3/Source.cpp
> +	int n;
Аа, неинициализированная переменная. К тому же, ненужная, можно было `scanf("%*d");`, а ещё лучше можно было правильно выставить опции проекта, чтобы окно не закрывалось.

2018-10-07 22:29 UTC, merged